### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by 11TStudio** [11TStudio/SquadStatsJSPRO#2]
## ToDo
- [x] Delete unused code + files
- [ ] Basic stat page
- [ ] Leaderboard command
- [ ] TOP 3 Medics
- [ ] TOP 3 CMD's
- [ ] TOP 3 Most Active (experience/points)
- [ ] TOP 3 INF (Wounds made with a riffle)
- [ ] Sperate the profile command (un-link - link - profile?)
- [x] Clear out the language files
